config/routes.rb
Rails.application.routes.draw do
  # Root Path
  match '*any' => 'application#options', :via => [:options]
  root 'posts#index'
  get 'tags/:tag', to: 'posts#index', as: :tag

  # Sessions
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Password Resets 
  get 'password_resets/new'
  get 'password_resets/edit'

  # Pages
  get 'admin' => 'pages#admin'
  get 'about' => 'pages#about'
  get 'signup'  => 'users#new'
  get '/codepen', to: 'posts#codepen', defaults: { format: 'json' }
  get 'feed' => 'posts#index', defaults: { format: 'atom' }
 
  # Model Pages
  resources :posts, except: [:show, :codepen] do 
    resources :comments, only: [ :create ]
  end

  resources :categories, except: [:show]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  # Category Show
  get '/:permalink', to: 'categories#show'
  
  # Post Show
  get '/:category/:permalink', to: 'posts#show', as: :post_show



end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:notice] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:error] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end

  def update
    if password_blank?
      flash.now[:error] = "Password can't be blank"
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Returns true if password is blank.
    def password_blank?
      params[:user][:password].blank?
    end

    # Before filters

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:error] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div id="formPage" class="boxPadding">
  <header>
    <h2>Reset Password</h2>
    <p>Fill out the form below to complete your password reset.</p>
  </header>

  <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
    <fieldset>
      <%= hidden_field_tag :email, @user.email %>
      <%= f.label :password %>
      <%= f.password_field :password, :placeholder => "New Password" %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :placeholder => 'Password Confirmation' %>
      <%= f.submit "Submit", :class => "greenButton" %>
    </fieldset>
  <% end %>

app/views/password_resets/new.html.erb
<% @title="Forgot your password?" %>

<div class="form-page">

  <header>
    <h2>Forgot your password?</h2>
  </header>

  <%= form_for(:password_reset, url: password_resets_path) do |f| %>
    
    <fieldset>
      <div class="relative field">
       <%= f.label :email %>
        <%= f.email_field :email, :placeholder => 'Email', :class => "icond" %>
        <svg class="user-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 9.4 10.3"><path d="M7.6,10.3H1.8C0.7,10.3,0,9.6,0,8.6C0,7,0.4,4.7,2.3,4.7c0.2,0,1.1,0.9,2.4,0.9s2.2-0.9,2.4-0.9c2,0,2.3,2.3,2.3,3.8C9.4,9.6,8.7,10.3,7.6,10.3z M4.7,5.1C3.3,5.1,2.1,4,2.1,2.6S3.3,0,4.7,0s2.6,1.2,2.6,2.6S6.1,5.1,4.7,5.1z"/></svg>
      </div>

      <div class="field">
        <%= f.submit "Submit", :class => "blue-button" %>
      </div>
    </fieldset>

  <% end %>

  <div class="form-foot-links">
    <p><%= link_to "Sign up now!", signup_path %></p>
    <p><%= link_to "Login", login_path %></p>
  </div>

</div>



