config/routes.rb
Rails.application.routes.draw do
  # Root Path
  match '*any' => 'application#options', :via => [:options]
  root 'posts#index'
  get 'tags/:tag', to: 'posts#index', as: :tag

  # Sessions
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Password Resets 
  get 'password_resets/new'
  get 'password_resets/edit'

  # Pages
  get 'admin' => 'pages#admin'
  get 'about' => 'pages#about'
  get 'signup'  => 'users#new'
  get '/codepen', to: 'posts#codepen', defaults: { format: 'json' }
  get 'feed' => 'posts#index', defaults: { format: 'atom' }
 
  # Model Pages
  resources :posts, except: [:show, :codepen] do 
    resources :comments, only: [ :create ]
  end

  resources :categories, except: [:show]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  # Category Show
  get '/:permalink', to: 'categories#show'
  
  # Post Show
  get '/:category/:permalink', to: 'posts#show', as: :post_show



end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:notice] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admin_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:error] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<fieldset>
  <%= form_for(@user) do |f| %>
    
    <div class="relative field">
      <%= f.label :name %>
      <%= f.text_field :name, :placeholder => 'Username', :class => 'icond' %>
      <svg class="name-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10.3 10.3"><path d="M5.1,10.3C2.3,10.3,0,8,0,5.1S2.3,0,5.1,0s5.1,2.3,5.1,5.1S8,10.3,5.1,10.3z M5.1,0.9c-2.4,0-4.3,1.9-4.3,4.3s1.9,4.3,4.3,4.3s4.3-1.9,4.3-4.3S7.5,0.9,5.1,0.9z M3.4,4.3C3,4.3,2.6,3.9,2.6,3.4S3,2.6,3.4,2.6S4.3,3,4.3,3.4S3.9,4.3,3.4,4.3z M5.1,8.1C4,8.1,3,7.4,2.7,6.3C2.6,6.1,2.7,5.9,3,5.8c0.2-0.1,0.5,0.1,0.5,0.3c0.2,0.7,0.9,1.2,1.6,1.2s1.4-0.5,1.6-1.2c0.1-0.2,0.3-0.4,0.5-0.3c0.2,0.1,0.3,0.3,0.3,0.5C7.3,7.4,6.3,8.1,5.1,8.1z M6.9,4.3C6.4,4.3,6,3.9,6,3.4s0.4-0.9,0.9-0.9S7.7,3,7.7,3.4S7.3,4.3,6.9,4.3z"/></svg>
    </div>
    
    <div class="relative field">
      <%= f.label :email %>
      <%= f.email_field :email, :placeholder => 'Email', :class => "icond" %>
      <svg class="user-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 9.4 10.3"><path d="M7.6,10.3H1.8C0.7,10.3,0,9.6,0,8.6C0,7,0.4,4.7,2.3,4.7c0.2,0,1.1,0.9,2.4,0.9s2.2-0.9,2.4-0.9c2,0,2.3,2.3,2.3,3.8C9.4,9.6,8.7,10.3,7.6,10.3z M4.7,5.1C3.3,5.1,2.1,4,2.1,2.6S3.3,0,4.7,0s2.6,1.2,2.6,2.6S6.1,5.1,4.7,5.1z"/></svg>
    </div>

    <div class="relative field">
      <%= f.label :password %>
      <%= f.password_field :password, :placeholder => 'Password', :class => "icond" %>
      <svg class="password-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 7.7 9.4"><path d="M7.7,8.8c0,0.4-0.3,0.6-0.6,0.6H0.6C0.3,9.4,0,9.1,0,8.8V4.9c0-0.4,0.3-0.6,0.6-0.6h0.2V3c0-1.6,1.4-3,3-3s3,1.4,3,3v1.3h0.2c0.4,0,0.6,0.3,0.6,0.6V8.8z M5.6,4.3V3c0-0.9-0.8-1.7-1.7-1.7S2.1,2.1,2.1,3v1.3H5.6z"/></svg>
    </div>

    <div class="relative field">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, :placeholder => 'Password Confirmation', :class => "icond" %>
      <svg class="password-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 7.7 9.4"><path d="M7.7,8.8c0,0.4-0.3,0.6-0.6,0.6H0.6C0.3,9.4,0,9.1,0,8.8V4.9c0-0.4,0.3-0.6,0.6-0.6h0.2V3c0-1.6,1.4-3,3-3s3,1.4,3,3v1.3h0.2c0.4,0,0.6,0.3,0.6,0.6V8.8z M5.6,4.3V3c0-0.9-0.8-1.7-1.7-1.7S2.1,2.1,2.1,3v1.3H5.6z"/></svg>
    </div>

    <div class="field">
      <%= f.submit "Create my account", :class => "blue-button" %>
    </div>

  <% end %>
</fieldset>





app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
    <% if current_user.admin? && current_user?(user) %>
      <a>
        <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
      </a>
    <% end %>
  <% end %>
</ul>

app/views/users/new.html.erb
<% @title="Signup" %>

<div class="form-page">

 <% if @user.errors.any? %>
      <ul id="errors">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>

  <header>
    <h2>Signup for Sitechop</h2>
  </header>
  <%= render 'form' %>
  <div class="form-foot-links">
    <p><%= link_to 'Log in', login_path %></p>
    <p><%= link_to "Forgot Password?", password_resets_new_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<h1>
  Hello world
  <% if logged_in? %>
    <p>You're Logged in</p>
  <% else %>
    <p>Your logged out</p>
  <% end %>
</h1>

