config/routes.rb
Rails.application.routes.draw do
  # Root Path
  match '*any' => 'application#options', :via => [:options]
  root 'posts#index'
  get 'tags/:tag', to: 'posts#index', as: :tag

  # Sessions
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Password Resets 
  get 'password_resets/new'
  get 'password_resets/edit'

  # Pages
  get 'admin' => 'pages#admin'
  get 'about' => 'pages#about'
  get 'signup'  => 'users#new'
  get '/codepen', to: 'posts#codepen', defaults: { format: 'json' }
  get 'feed' => 'posts#index', defaults: { format: 'atom' }
 
  # Model Pages
  resources :posts, except: [:show, :codepen] do 
    resources :comments, only: [ :create ]
  end

  resources :categories, except: [:show]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  # Category Show
  get '/:permalink', to: 'categories#show'
  
  # Post Show
  get '/:category/:permalink', to: 'posts#show', as: :post_show



end

app/views/pages/about.html.erb
<h2>Pages#about</h2>
<p>Find me in app/views/pages/about.html.erb</p>

<%= content_tag "canvas", height: "300", width: "900", id: "canvas", data: {url: @posts.count} do %>
<% end %>

<p></p>

app/views/pages/admin.html.erb
<style>
table {
  width: 100%;
}
  td {
    padding: .5em .75em;

  }

  thead th{
    padding: 1em;
    background: #ccc;
  }

    tbody tr:nth-child(odd) {
      background: #eee;
    }
    .tBut {
      text-align: center;
    }

    .hide {
      display: none;
    }
</style>

<div id="adminZone" class="mediumWidthWrapper">
  
  <h2>Administration</h2>

  <h3>Blog posts</h3>

  <table>
    <thead>
    <tr>
      <th>Post Title</th>
      <th>Edit Post</th>    
      <th>Delete Post</th>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post.url %></td>
        <td class="tBut"><%= link_to "Edit Post", edit_post_path(post), :class => "blueButton" %></td>    
        <td class="tBut"><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"redButton" %></td>
      </tr>
    <% end %>
    </tbody>  
  </table>

  <%= link_to 'New Post', new_post_path, :class => "greenButton" %>



  <h3>Categories</h3>

  <table>
    <thead>
    <tr>
      <th>Category Title</th>
      <th>Edit Category</th>    
      <th>Delete Category</th>
    </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.title, category.url %></td>
          <td class="tBut"><%= link_to "Edit", edit_category_path(category), :class => "blueButton" %></td>    
          <td class="tBut"><%= link_to 'Destroy', category_path(category), :class=>"redButton", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>       
      <% end %>
    </tbody>  
  </table>

  <%= link_to 'New Category', new_category_path, :class => "greenButton" %>


  <h3>Users</h3>

  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Activated?</th>
      <th>Delete User</th>
    </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.activated? %></td>
          <td class="tBut"><%= link_to 'Destroy', user_path(user), :class=>"redButton", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>       
      <% end %>
    </tbody>  
  </table>
</div>