config/routes.rb
Rails.application.routes.draw do
  # Root Path
  match '*any' => 'application#options', :via => [:options]
  root 'posts#index'
  get 'tags/:tag', to: 'posts#index', as: :tag

  # Sessions
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Password Resets 
  get 'password_resets/new'
  get 'password_resets/edit'

  # Pages
  get 'admin' => 'pages#admin'
  get 'about' => 'pages#about'
  get 'signup'  => 'users#new'
  get '/codepen', to: 'posts#codepen', defaults: { format: 'json' }
  get 'feed' => 'posts#index', defaults: { format: 'atom' }
 
  # Model Pages
  resources :posts, except: [:show, :codepen] do 
    resources :comments, only: [ :create ]
  end

  resources :categories, except: [:show]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  # Category Show
  get '/:permalink', to: 'categories#show'
  
  # Post Show
  get '/:category/:permalink', to: 'posts#show', as: :post_show



end

app/views/layouts/_billboard.html.erb
<div class="billboard">
  <div class="width">

    <div class="billboard-text">
      <h2>Master The Web</h2>
      <p>Sitechop is a web design and development blog focused on HTML, CSS, JavaScript, Rails, Shopify, and much more. Signup for access to all sourcefiles and resources.</p>
      <a class="large-button blue-button">Signup for free!</a>
    </div>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="master-footer">
  <div class="footer-top width cf">

    <div class="footer-box">
      <h2>Navigate</h2>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><a href="mailto:sitechop@gmail.com">Contact</a></li>

        <% if logged_in? %>
          <li><%= link_to("Log out", logout_path, method: "delete") %></li>
        
          <% unless !current_user.admin? %>
            <li><%= link_to "Admin", admin_path %></li>
          <% end %>

        <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li><%= link_to "Signup", signup_path %></li>
        <% end %>
      </ul>
    </div>

    <div class="footer-box">
      <h2>Categories</h2>
      <ul>
        <li><a href="/front-end">Front End Development</a></li>
        <li><a href="/rails">Rails</a></li>
        <li><a href="/ubuntu">Ubuntu</a></li>
        <li><a href="/windows">Windows</a></li>
        <li><a href="/general">General</a></li>
      </ul>
    </div>

    <div class="footer-box">
      <h2>Social</h2>
      <ul>
        <li><a href="http://twitter.com/sitechop">Twitter</a></li>
        <li><a href="https://facebook.com/sitechop">Facebook</a></li>
        <li><a href="/feed">RSS Feed</a></li>
      </ul>
    </div>

  </div>

</footer>

app/views/layouts/_header.html.erb
<header class="master-header">
  <div class="width">

    <h1>Sitechop</h1>

    <nav class="master-nav">
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">Categories</a></li>
        <li><a href="#">Login</a></li>
        <li><a href="#">Signup</a></li>
        <li><a href="#">RSS</a></li>
      </ul>

      <form id="search">
        <input type="text" placeholder="Search">
        <input type="submit" value="Search">
      </form>
    </nav>

    <a class="hamburger">Menu</a>

  </div>
</header>

app/views/layouts/_post_sidebar.erb
<div class="side-column">

<% unless logged_in? %>
  <div class="sidebox join-today">
    <h3>Join Sitechop!</h3>
    <p>Signup or login for sitechop and unlock all source files, resources, commenting.</p>
    <%= link_to 'Signup for free!', signup_path %>
  </div>
<% end %>


<% unless !@post.source.present? && !@post.codepen.present? %>
  <div class="sidebox downloads-demos">
    <h3>Downloads &amp; Demos</h3>
    <ul class="cf">


    <% unless !@post.source.present? %>
      <li>
      <a <% if logged_in? %> href="<%= @post.source.url %>"> <% else %> href="/login"><% end %>
          <svg width="30px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22"><path d="M22,14.4c0,0.3-0.2,0.6-0.4,0.8l-10.1,6.7C11.4,22,11.2,22,11,22s-0.4-0.1-0.5-0.2L0.4,15.1C0.2,15,0,14.7,0,14.4V7.7C0,7.3,0.2,7,0.4,6.9l10.1-6.7C10.6,0.1,10.8,0,11,0s0.4,0.1,0.5,0.2l10.1,6.7C21.9,7,22,7.3,22,7.7V14.4z M4.3,11L1.9,9.4v3.2L4.3,11z M10.1,7.1V2.7L2.7,7.7L6,9.9L10.1,7.1z M10.1,19.3v-4.4L6,12.1l-3.3,2.2L10.1,19.3z M14.3,11L11,8.8L7.7,11l3.3,2.2L14.3,11z M19.4,7.7L12,2.7v4.4l4.1,2.7L19.4,7.7z M19.4,14.4l-3.3-2.2L12,14.9v4.4L19.4,14.4z M20.1,12.6V9.4L17.7,11L20.1,12.6z"/></svg>
          Download Source
        </a>
      </li>
  <% end %>


      <% unless !@post.codepen.present? %>
        <li class="source">
          <a href="<%= @post.codepen_url %>">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26.5 19.9" width="34px"><path d="M7.6,17.1c-0.2,0.2-0.5,0.2-0.7,0l-6.8-6.8C0,10.1,0,9.8,0.1,9.6l6.8-6.8c0.2-0.2,0.5-0.2,0.7,0l0.7,0.7c0.2,0.2,0.2,0.5,0,0.7L2.6,10l5.7,5.7c0.2,0.2,0.2,0.5,0,0.7L7.6,17.1z M11.5,19.6c-0.1,0.2-0.3,0.4-0.6,0.3L10,19.7c-0.2-0.1-0.4-0.3-0.3-0.6l5.4-18.7c0.1-0.2,0.3-0.4,0.6-0.3l0.9,0.2c0.2,0.1,0.4,0.3,0.3,0.6L11.5,19.6z M19.6,17.1c-0.2,0.2-0.5,0.2-0.7,0l-0.7-0.7c-0.2-0.2-0.2-0.5,0-0.7L24,10l-5.7-5.7c-0.2-0.2-0.2-0.5,0-0.7L19,2.9c0.2-0.2,0.5-0.2,0.7,0l6.8,6.8c0.2,0.2,0.2,0.5,0,0.7L19.6,17.1z"/></svg>
            Codepen Demo
          </a>
        </li>
      <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="sidebox post-directory">
  </div>

  <div class="sidebox tag-box">
    <h3>Tagged With</h3>
    <ul>
      <% @post.tag_counts.each do |tag| %>
        <li><%= link_to tag.name, tag_path(tag.name) %></li>
      <% end %>
    </ul>
  </div>

  <div class="sidebox share-post">
    <h3>Share this post</h3>
    <ul>

      <li>
        <a class="twitter-share" href="#">
          <div class="share-icon twitter-share-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="white" width="20px" viewBox="0 0 10.6 8.6"><path d="M9.5,2.1c0,0.1,0,0.2,0,0.3c0,2.9-2.2,6.2-6.2,6.2C2.1,8.6,1,8.2,0,7.6c0.2,0,0.3,0,0.5,0c1,0,1.9-0.3,2.7-0.9c-1,0-1.7-0.6-2-1.5c0.1,0,0.3,0,0.4,0c0.2,0,0.4,0,0.6-0.1C1.2,5,0.4,4.1,0.4,3c0,0,0,0,0,0c0.3,0.2,0.6,0.3,1,0.3c-0.6-0.4-1-1.1-1-1.8c0-0.4,0.1-0.8,0.3-1.1c1.1,1.3,2.7,2.2,4.5,2.3c0-0.2-0.1-0.3-0.1-0.5C5.1,1,6.1,0,7.3,0c0.6,0,1.2,0.3,1.6,0.7c0.5-0.1,1-0.3,1.4-0.5c-0.2,0.5-0.5,0.9-1,1.2c0.4,0,0.9-0.2,1.2-0.3C10.3,1.4,9.9,1.8,9.5,2.1z"></path></svg>
          </div>

          <span>Share on Twitter</span>
        </a>
      </li>
      <li>
        <a class="facebook-share" href="#">
          <div class="share-icon facebook-share-icon">
          <svg fill="#55acee" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 5.8 11.1" fill="white" width="10px"><path d="M5.8,1.8H4.7c-0.8,0-1,0.4-1,1v1.3h2l-0.3,2H3.8v5.1h-2V6.1H0v-2h1.7V2.6c0-1.7,1-2.6,2.6-2.6C5,0,5.6,0.1,5.8,0.1V1.8z"></path></svg>
          </div>

          <span>Share on Facebook</span>
        </a>
      </li>
    </ul>
  </div>



</div>

app/views/layouts/_sidebar.html.erb
<div class="side-column cf">

  <% if params[:controller] == 'posts' && params[:action] == 'show' %>


    <% unless !@post.source.present? && !@post.codepen.present? %>
      <div class="sidebox demos">
        <h2>Downloads &amp; Demos</h2>
        <ul>

          <% unless !@post.source.present? %>
            <li class="slide-button">
              <a class="download-source" <% if logged_in? %>href="<%= @post.source.url %>"> <% else %> href="/login"><% end %>
                <div class="share-icon source-icon">
                  <svg width="20px" fill="white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22"><path d="M22,14.4c0,0.3-0.2,0.6-0.4,0.8l-10.1,6.7C11.4,22,11.2,22,11,22s-0.4-0.1-0.5-0.2L0.4,15.1C0.2,15,0,14.7,0,14.4V7.7C0,7.3,0.2,7,0.4,6.9l10.1-6.7C10.6,0.1,10.8,0,11,0s0.4,0.1,0.5,0.2l10.1,6.7C21.9,7,22,7.3,22,7.7V14.4z M4.3,11L1.9,9.4v3.2L4.3,11z M10.1,7.1V2.7L2.7,7.7L6,9.9L10.1,7.1z M10.1,19.3v-4.4L6,12.1l-3.3,2.2L10.1,19.3z M14.3,11L11,8.8L7.7,11l3.3,2.2L14.3,11z M19.4,7.7L12,2.7v4.4l4.1,2.7L19.4,7.7z M19.4,14.4l-3.3-2.2L12,14.9v4.4L19.4,14.4z M20.1,12.6V9.4L17.7,11L20.1,12.6z"/></svg>
                </div>
                <span>Download Source</span>
              </a>
            </li>
          <% end %>

          <% unless !@post.codepen.present? %>
            <li class="slide-button">
              <a class="codepen-demo" href="<%= @post.codepen_url %>">
                <div class="share-icon codepen-icon">
                  <svg fill="white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26.5 19.9" width="20px"><path d="M7.6,17.1c-0.2,0.2-0.5,0.2-0.7,0l-6.8-6.8C0,10.1,0,9.8,0.1,9.6l6.8-6.8c0.2-0.2,0.5-0.2,0.7,0l0.7,0.7c0.2,0.2,0.2,0.5,0,0.7L2.6,10l5.7,5.7c0.2,0.2,0.2,0.5,0,0.7L7.6,17.1z M11.5,19.6c-0.1,0.2-0.3,0.4-0.6,0.3L10,19.7c-0.2-0.1-0.4-0.3-0.3-0.6l5.4-18.7c0.1-0.2,0.3-0.4,0.6-0.3l0.9,0.2c0.2,0.1,0.4,0.3,0.3,0.6L11.5,19.6z M19.6,17.1c-0.2,0.2-0.5,0.2-0.7,0l-0.7-0.7c-0.2-0.2-0.2-0.5,0-0.7L24,10l-5.7-5.7c-0.2-0.2-0.2-0.5,0-0.7L19,2.9c0.2-0.2,0.5-0.2,0.7,0l6.8,6.8c0.2,0.2,0.2,0.5,0,0.7L19.6,17.1z"/></svg>
                </div>
                <span>Codepen Demo</span>
              </a>
            </li>
          <% end %>

        </ul>
      </div>
      <% end %>


      <div class="sidebox share-post">
        <h2>Share this post</h2>
        <ul>

          <li class="slide-button">
            <a class="twitter-share" title="<%= @post.title %>" href="http://sitechop.com<%= @post.url %>">
              <div class="share-icon twitter-share-icon">
                <svg xmlns="http://www.w3.org/2000/svg" fill="white" width="20px" viewBox="0 0 10.6 8.6"><path d="M9.5,2.1c0,0.1,0,0.2,0,0.3c0,2.9-2.2,6.2-6.2,6.2C2.1,8.6,1,8.2,0,7.6c0.2,0,0.3,0,0.5,0c1,0,1.9-0.3,2.7-0.9c-1,0-1.7-0.6-2-1.5c0.1,0,0.3,0,0.4,0c0.2,0,0.4,0,0.6-0.1C1.2,5,0.4,4.1,0.4,3c0,0,0,0,0,0c0.3,0.2,0.6,0.3,1,0.3c-0.6-0.4-1-1.1-1-1.8c0-0.4,0.1-0.8,0.3-1.1c1.1,1.3,2.7,2.2,4.5,2.3c0-0.2-0.1-0.3-0.1-0.5C5.1,1,6.1,0,7.3,0c0.6,0,1.2,0.3,1.6,0.7c0.5-0.1,1-0.3,1.4-0.5c-0.2,0.5-0.5,0.9-1,1.2c0.4,0,0.9-0.2,1.2-0.3C10.3,1.4,9.9,1.8,9.5,2.1z"></path></svg>
              </div>

              <span>Share on Twitter</span>
            </a>
          </li>
          <li class="slide-button">
            <a class="facebook-share" href="http://www.facebook.com/share.php?u=http://sitechop.com<%= @post.url %>" onclick="return fbs_click()" target="_blank">
              <div class="share-icon facebook-share-icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 5.8 11.1" fill="white" width="10px"><path d="M5.8,1.8H4.7c-0.8,0-1,0.4-1,1v1.3h2l-0.3,2H3.8v5.1h-2V6.1H0v-2h1.7V2.6c0-1.7,1-2.6,2.6-2.6C5,0,5.6,0.1,5.8,0.1V1.8z"></path></svg>
              </div>

              <span>Share on Facebook</span>
            </a>
          </li>
        </ul>
      </div>
  <% else %>

  <div class="sidebox tag-box">
    <h2>Popular Tags</h2>

    <ul>
      <% Post.tag_counts.each do |tag| %>
        <li><%= link_to tag.name, tag_path(tag.name) %></li>
      <% end %>
    </ul>
  </div>

  <div class="sidebox share-post">
    <h2>Follow Us</h2>
    <ul>
      <li class="slide-button">
        <a class="twitter-share" href="http://twitter.com/sitechop">
          <div class="share-icon twitter-share-icon">
            <svg xmlns="http://www.w3.org/2000/svg" fill="white" width="20px" viewBox="0 0 10.6 8.6"><path d="M9.5,2.1c0,0.1,0,0.2,0,0.3c0,2.9-2.2,6.2-6.2,6.2C2.1,8.6,1,8.2,0,7.6c0.2,0,0.3,0,0.5,0c1,0,1.9-0.3,2.7-0.9c-1,0-1.7-0.6-2-1.5c0.1,0,0.3,0,0.4,0c0.2,0,0.4,0,0.6-0.1C1.2,5,0.4,4.1,0.4,3c0,0,0,0,0,0c0.3,0.2,0.6,0.3,1,0.3c-0.6-0.4-1-1.1-1-1.8c0-0.4,0.1-0.8,0.3-1.1c1.1,1.3,2.7,2.2,4.5,2.3c0-0.2-0.1-0.3-0.1-0.5C5.1,1,6.1,0,7.3,0c0.6,0,1.2,0.3,1.6,0.7c0.5-0.1,1-0.3,1.4-0.5c-0.2,0.5-0.5,0.9-1,1.2c0.4,0,0.9-0.2,1.2-0.3C10.3,1.4,9.9,1.8,9.5,2.1z"></path></svg>
          </div>

          <span>Follow on Twitter</span>
        </a>
      </li>
      <li class="slide-button">
        <a class="facebook-share" href="http://facebook.com/sitechop">
          <div class="share-icon facebook-share-icon">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 5.8 11.1" fill="white" width="10px"><path d="M5.8,1.8H4.7c-0.8,0-1,0.4-1,1v1.3h2l-0.3,2H3.8v5.1h-2V6.1H0v-2h1.7V2.6c0-1.7,1-2.6,2.6-2.6C5,0,5.6,0.1,5.8,0.1V1.8z"></path></svg>
          </div>

          <span>Like on Facebook</span>
        </a>
      </li>
      <li class="slide-button">
        <a class="rss-sub" href="/feed">
          <div class="share-icon rss-icon">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 9.4 9.4" width="15px" fill="white"><path d="M9.3,9.3C9.2,9.4,9.1,9.4,9,9.4H8C7.8,9.4,7.6,9.3,7.6,9C7.4,5.1,4.3,2,0.4,1.8C0.2,1.8,0,1.6,0,1.4v-1c0-0.1,0-0.2,0.1-0.3C0.2,0,0.3,0,0.4,0c0,0,0,0,0,0C2.8,0.1,5,1.1,6.7,2.8C8.3,4.4,9.3,6.6,9.4,9C9.4,9.1,9.4,9.2,9.3,9.3z M5.9,9.3C5.8,9.4,5.7,9.4,5.6,9.4H4.7C4.4,9.4,4.3,9.3,4.2,9C4.1,7,2.4,5.4,0.4,5.2C0.2,5.2,0,5,0,4.8V3.9c0-0.1,0-0.2,0.1-0.3c0.1-0.1,0.2-0.1,0.3-0.1c0,0,0,0,0,0c1.4,0.1,2.8,0.7,3.8,1.8c1,1,1.6,2.4,1.8,3.8C6,9.1,6,9.2,5.9,9.3z M1.3,9.4C0.6,9.4,0,8.9,0,8.1s0.6-1.3,1.3-1.3s1.3,0.6,1.3,1.3S2,9.4,1.3,9.4z"/></svg>
          </div>

          <span>RSS Feed</span>
        </a>
      </li>
    </ul>
  </div>








</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= the_title %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:900' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <%= content_tag :p, value, class: "flash #{key}" %>
    <% end %>  

    <%= render 'layouts/billboard' %>


        <%= yield %>
    

   <% if params[:controller] == 'posts' && params[:action] == 'show' %>
       <%= render 'posts/similar' %>
    <% end %> 

        <%= render 'layouts/footer' %>


    </body>
</html>